package reflect

import (
	"fmt"
	"io"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/iancoleman/strcase"
	"github.com/pkg/errors"
	"xorm.io/xorm/schemas"
)

const (
	// DefaultPkgName 默认的包名
	DefaultPkgName = "models"
	// DefaultHeaderLine 生成文件的默认文件头
	DefaultHeaderLine = "Code generated by ezboot. DO NOT EDIT."
)

// render 是一个将表格生成到一个文件的生成器
type render struct {
	table *schemas.Table

	pkgName    string
	headerLine string

	structNameMapper StringMapper
	fieldAliasMapper []StringMapper
	fieldNameMapper  StringMapper
	fieldTagMappers  []TagMapper
	fieldTypeMappers []TypeMapper

	renderModelIdentifier *QualifiedIdentifier
	renderModelFields     map[string]*FieldQualifiedIdentifier

	daoWriter  io.Writer
	daoOptions []DAORenderOption
}

// Render 将当前表中的数据反射到Writer中
func (r *render) Render(w io.Writer) error {
	g := jen.NewFilePath(r.pkgName)

	g.HeaderComment(r.headerLine)
	g.Line()

	var outerErr error
	typename := r.structNameMapper.Mapping(r.table.Name)
	r.renderModelIdentifier = &QualifiedIdentifier{
		Import:     r.pkgName,
		Identifier: typename,
	}

	g.Commentf("%s is the model of table %s in the database", typename, r.table.Name)
	g.Type().Id(typename).StructFunc(func(gp *jen.Group) {
		for _, column := range r.table.Columns() {
			columnName := column.Name
			for _, mapper := range r.fieldAliasMapper {
				if mapping := mapper.Mapping(column.Name); len(mapping) != 0 {
					columnName = mapping
					break
				}
			}

			name := r.fieldNameMapper.Mapping(columnName)
			field, err := r.asField(name, column, gp.Id(name))
			if err != nil {
				outerErr = err
				return
			}

			tags := make(map[string]string)
			for _, mapper := range r.fieldTagMappers {
				tags[mapper.Name(field)] = mapper.Content(field)
			}
			field.stmt.Tag(tags)
		}
	})

	if outerErr != nil {
		return outerErr
	}

	receiver := jen.Op("*").Id(typename)
	g.Comment("TableName returns the name of the table corresponding to the current model")
	g.Func().Params(receiver).Id("TableName").Params().String().BlockFunc(func(gp *jen.Group) {
		gp.Return(jen.Lit(r.table.Name))
	})

	g.Line() // trailing line
	if err := g.Render(w); err != nil {
		return err
	}

	if r.daoWriter != nil {
		// dao render
		dr, err := newDAORender(r, r.daoOptions...)
		if err != nil {
			return err
		}
		return dr.Render(r.daoWriter)
	}

	return nil
}

// asField 将一个数据库字段转换为一个结构体字段描述
func (r *render) asField(name string, column *schemas.Column, stmt *jen.Statement) (*Field, error) {
	v := r.mapping(column, r.table)
	if v == nil {
		return nil, errors.Errorf("render: unknown type of column %q", column.Name)
	}

	qi, err := AsQualifiedIdentifier(v)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to reflect the column type %#v", v)
	}
	if qi.Pointer {
		return nil, errors.Errorf("unsupported pointer type field %q", v)
	}

	if r.renderModelFields == nil {
		r.renderModelFields = make(map[string]*FieldQualifiedIdentifier)
	}

	r.renderModelFields[column.Name] = &FieldQualifiedIdentifier{
		FieldName:  name,
		PrimaryKey: column.IsPrimaryKey,
		Identifier: &QualifiedIdentifier{
			Pointer:    qi.Pointer,
			Import:     qi.Import,
			Identifier: qi.Identifier,
		},
	}

	return &Field{
		Column: column,
		Name:   name,
		Type: &FieldType{
			Value:      v,
			Identifier: qi,
		},
		stmt: stmt.Add(qi.AsCode()),
	}, nil
}

// mapping 根据数据库字段和表格等相关信息映射字段的类型
func (r *render) mapping(column *schemas.Column, table *schemas.Table) any {
	for i := len(r.fieldTypeMappers) - 1; i >= 0; i-- {
		v := r.fieldTypeMappers[i].Mapping(column, table)
		if v != nil {
			return v
		}
	}
	return nil
}

// newRender 创建一个渲染器
func newRender(table *schemas.Table, options ...RenderOption) (*render, error) {
	r := &render{
		table: table,

		pkgName:    DefaultPkgName,
		headerLine: DefaultHeaderLine,

		structNameMapper: CamelcaseMapper(),
		fieldNameMapper:  CamelcaseMapper(),
		fieldTypeMappers: []TypeMapper{DefaultTypeMapper()},
	}

	for _, option := range options {
		if err := option(r); err != nil {
			return nil, err
		}
	}
	return r, nil
}

// RenderOption 是额外的渲染配置
type RenderOption func(*render) error

// WithPkgName 指定生成文件的包名
func WithPkgName(pkg string) RenderOption {
	return func(r *render) error {
		r.pkgName = pkg
		return nil
	}
}

// WithPkgPath 指定生成文件的所在路径
func WithPkgPath(path string) RenderOption {
	return func(r *render) error {
		r.pkgName = path
		return nil
	}
}

// WithHeaderLine 指定生成文件的头行
func WithHeaderLine(line string) RenderOption {
	return func(r *render) error {
		r.headerLine = line
		return nil
	}
}

// StringMapper 是一个字符串映射的接口定义
type StringMapper interface {
	// Mapping 将一个字符串映射到另一个字符串
	Mapping(s string) string
}

// WithStructNameMapper 结构体名称的映射器
func WithStructNameMapper(mapper StringMapper) RenderOption {
	return func(r *render) error {
		r.structNameMapper = mapper
		return nil
	}
}

// WithFieldNameMapper 是结构体字段名称的映射器
func WithFieldNameMapper(mapper StringMapper) RenderOption {
	return func(r *render) error {
		r.fieldNameMapper = mapper
		return nil
	}
}

// WithFiledAliasMapper 为数据库字段起别名的映射器
func WithFiledAliasMapper(mapper StringMapper) RenderOption {
	return func(r *render) error {
		r.fieldAliasMapper = append(r.fieldAliasMapper, mapper)
		return nil
	}
}

// StringMapperFunc 是函数形式的字符串映射器
type StringMapperFunc func(s string) string

// Mapping 将一个字符串映射到另一个字符串
func (f StringMapperFunc) Mapping(s string) string {
	return f(s)
}

// CamelcaseMapper 驼峰形式的名称转换器
func CamelcaseMapper() StringMapperFunc {
	return func(s string) string {
		return strcase.ToCamel(s)
	}
}

// TagMapper 是一个为结构体字段添加标签的映射器
type TagMapper interface {
	// Name 返回标签的名字
	Name(field *Field) string
	// Content 返回标签的内容
	Content(field *Field) string
}

// WithFieldTagMapper 添加一个新的标签映射器
func WithFieldTagMapper(mapper TagMapper) RenderOption {
	return func(r *render) error {
		r.fieldTagMappers = append(r.fieldTagMappers, mapper)
		return nil
	}
}

// TagContentMapperFunc 是一个经过简化的字段标签映射器
type TagContentMapperFunc func(field *Field) string

// WithFieldTagMapperFunc 配置一个固定名字的标签映射器
func WithFieldTagMapperFunc(tag string, mapper TagContentMapperFunc) RenderOption {
	return func(r *render) error {
		r.fieldTagMappers = append(r.fieldTagMappers, &FixedNameTagMapper{Tag: tag, Mapper: mapper})
		return nil
	}
}

// FixedNameTagMapper 固定名字的标签映射器
type FixedNameTagMapper struct {
	Tag    string
	Mapper TagContentMapperFunc
}

// Name 返回标签的名字
func (m *FixedNameTagMapper) Name(*Field) string {
	return m.Tag
}

// Content 返回标签的内容
func (m *FixedNameTagMapper) Content(field *Field) string {
	return m.Mapper(field)
}

// JsonTagMapper 映射一个下划线形式的 JSON 标签
func JsonTagMapper() TagMapper {
	return &FixedNameTagMapper{
		Tag: "json",
		Mapper: func(field *Field) string {
			return strcase.ToSnake(field.Name)
		},
	}
}

// YamlTagMapper 映射一个下划线形式的 YAML 标签
func YamlTagMapper() TagMapper {
	return &FixedNameTagMapper{
		Tag: "yaml",
		Mapper: func(field *Field) string {
			return strcase.ToSnake(field.Name)
		},
	}
}

// XORMTagMapper 是一个必备生成器
func XORMTagMapper() TagMapper {
	return &FixedNameTagMapper{
		Tag: "xorm",
		Mapper: func(field *Field) string {
			column := field.Column

			var attributes []string
			attributes = append(attributes, fmt.Sprintf(`'%s'`, column.Name))

			typename := strings.ToLower(column.SQLType.Name)
			if column.SQLType.DefaultLength != 0 {
				typename += fmt.Sprintf("(%d)", column.SQLType.DefaultLength)
			}
			attributes = append(attributes, typename)

			if column.IsPrimaryKey {
				attributes = append(attributes, "pk")
			} else {
				if !column.Nullable {
					attributes = append(attributes, "not null")
				}
			}

			if column.IsAutoIncrement {
				attributes = append(attributes, "autoincr")
			}

			switch column.Name {
			case "created_time", "create_time":
				attributes = append(attributes, "created")
			case "updated_time", "update_time":
				attributes = append(attributes, "updated")
			case "_version":
				attributes = append(attributes, "version")
			}

			if len(column.Comment) != 0 {
				attributes = append(attributes, fmt.Sprintf(`comment('%s')`, column.Comment))
			}

			return strings.Join(attributes, " ")
		},
	}
}

// WithDAORender 生成数据访问层的内容
func WithDAORender(w io.Writer, options ...DAORenderOption) RenderOption {
	return func(r *render) error {
		r.daoWriter = w
		r.daoOptions = append(r.daoOptions, options...)
		return nil
	}
}

// WithDAORenderOptions 生成数据访问层的内容
func WithDAORenderOptions(options ...DAORenderOption) RenderOption {
	return func(r *render) error {
		r.daoOptions = append(r.daoOptions, options...)
		return nil
	}
}

// FieldQualifiedIdentifier 数据库字段的映射关系
type FieldQualifiedIdentifier struct {
	FieldName  string
	PrimaryKey bool
	Identifier *QualifiedIdentifier
}
