// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/pberr/error.proto

package pberr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 配置 gRPC 错误对应的状态码
type WithHttpStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Http状态码
	HttpCode      uint32 `protobuf:"varint,1,opt,name=http_code,json=httpCode,proto3" json:"http_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithHttpStatus) Reset() {
	*x = WithHttpStatus{}
	mi := &file_internal_pberr_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithHttpStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithHttpStatus) ProtoMessage() {}

func (x *WithHttpStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pberr_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithHttpStatus.ProtoReflect.Descriptor instead.
func (*WithHttpStatus) Descriptor() ([]byte, []int) {
	return file_internal_pberr_error_proto_rawDescGZIP(), []int{0}
}

func (x *WithHttpStatus) GetHttpCode() uint32 {
	if x != nil {
		return x.HttpCode
	}
	return 0
}

type WithCauseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CauseError    string                 `protobuf:"bytes,1,opt,name=cause_error,json=causeError,proto3" json:"cause_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithCauseError) Reset() {
	*x = WithCauseError{}
	mi := &file_internal_pberr_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithCauseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithCauseError) ProtoMessage() {}

func (x *WithCauseError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pberr_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithCauseError.ProtoReflect.Descriptor instead.
func (*WithCauseError) Descriptor() ([]byte, []int) {
	return file_internal_pberr_error_proto_rawDescGZIP(), []int{1}
}

func (x *WithCauseError) GetCauseError() string {
	if x != nil {
		return x.CauseError
	}
	return ""
}

var File_internal_pberr_error_proto protoreflect.FileDescriptor

const file_internal_pberr_error_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/pberr/error.proto\x12\x14ezboot.internal.pberr\"-\n" +
	"\x0eWithHttpStatus\x12\x1b\n" +
	"\thttp_code\x18\x01 \x01(\rR\bhttpCode\"1\n" +
	"\x0eWithCauseError\x12\x1f\n" +
	"\vcause_error\x18\x01 \x01(\tR\n" +
	"causeErrorB\xca\x01\n" +
	"\x18com.ezboot.internal.pberrB\n" +
	"ErrorProtoP\x01Z0github.com/ez4bk/ezboot/internal/pberr\xa2\x02\x03XIP\xaa\x02\x14EZboot.Internal.Pberr\xca\x02\x14EZboot\\Internal\\Pberr\xe2\x02 EZboot\\Internal\\Pberr\\GPBMetadata\xea\x02\x16EZboot::Internal::Pberrb\x06proto3"

var (
	file_internal_pberr_error_proto_rawDescOnce sync.Once
	file_internal_pberr_error_proto_rawDescData []byte
)

func file_internal_pberr_error_proto_rawDescGZIP() []byte {
	file_internal_pberr_error_proto_rawDescOnce.Do(func() {
		file_internal_pberr_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pberr_error_proto_rawDesc), len(file_internal_pberr_error_proto_rawDesc)))
	})
	return file_internal_pberr_error_proto_rawDescData
}

var file_internal_pberr_error_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_pberr_error_proto_goTypes = []any{
	(*WithHttpStatus)(nil), // 0: ezboot.internal.pberr.WithHttpStatus
	(*WithCauseError)(nil), // 1: ezboot.internal.pberr.WithCauseError
}
var file_internal_pberr_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pberr_error_proto_init() }
func file_internal_pberr_error_proto_init() {
	if File_internal_pberr_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pberr_error_proto_rawDesc), len(file_internal_pberr_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pberr_error_proto_goTypes,
		DependencyIndexes: file_internal_pberr_error_proto_depIdxs,
		MessageInfos:      file_internal_pberr_error_proto_msgTypes,
	}.Build()
	File_internal_pberr_error_proto = out.File
	file_internal_pberr_error_proto_goTypes = nil
	file_internal_pberr_error_proto_depIdxs = nil
}
