package gengo

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

// SupportedFeatures reports the set of supported protobuf language features
var SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

var (
	pkgGrpcBoot = protogen.GoImportPath("github.com/ez4bk/ezboot")
)

// GenerateFile generates the contents of a .pb.go file
func GenerateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_ezboot.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	genGeneratedHeader(g, file)
	genVersionHeader(gen, g)
	genGoPackageHeader(g, file)
	genInitServiceClient(g, file)

	return g
}

func genInitServiceClient(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("var _ *", pkgGrpcBoot.Ident("ServerType"))
	g.P()

	g.P("func init() {")
	for _, service := range file.Services {
		constructor := "New" + service.GoName + "Client"
		g.P(pkgGrpcBoot.Ident("RegisterClient"), fmt.Sprintf(`("_", %s)`, constructor))
		_ = service
	}
	g.P("}")
}

func genGeneratedHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-ezboot. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
}

func genGoPackageHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("package ", file.GoPackageName)
	g.P()
}

func genVersionHeader(gen *protogen.Plugin, g *protogen.GeneratedFile) {
	g.P("// protoc: ", compilerVersion(gen))
	g.P("// protoc-gen-go-ezboot: ", Version)
	g.P()
}

func compilerVersion(gen *protogen.Plugin) string {
	ver := gen.Request.GetCompilerVersion()
	if ver == nil {
		return "(unknown)"
	}

	var suffix string
	if s := ver.GetSuffix(); s != "" {
		suffix = "-" + s
	}

	return fmt.Sprintf("v%d.%d.%d%s",
		ver.GetMajor(), ver.GetMinor(), ver.GetPatch(), suffix)
}
