// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/gin-boot/middleware/validatepb/validate.proto

package validatepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateError) Reset() {
	*x = ValidateError{}
	mi := &file_internal_gin_boot_middleware_validatepb_validate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateError) ProtoMessage() {}

func (x *ValidateError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gin_boot_middleware_validatepb_validate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateError.ProtoReflect.Descriptor instead.
func (*ValidateError) Descriptor() ([]byte, []int) {
	return file_internal_gin_boot_middleware_validatepb_validate_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidateError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_internal_gin_boot_middleware_validatepb_validate_proto protoreflect.FileDescriptor

const file_internal_gin_boot_middleware_validatepb_validate_proto_rawDesc = "" +
	"\n" +
	"6internal/gin-boot/middleware/validatepb/validate.proto\x12\n" +
	"validatepb\"=\n" +
	"\rValidateError\x12\x14\n" +
	"\x05Field\x18\x01 \x01(\tR\x05Field\x12\x16\n" +
	"\x06Reason\x18\x02 \x01(\tR\x06ReasonB\xb2\x01\n" +
	"\x0ecom.validatepbB\rValidateProtoP\x01ZIgithub.com/ez4bk/ezboot/internal/gin-boot/middleware/validatepb\xa2\x02\x03VXX\xaa\x02\n" +
	"Validatepb\xca\x02\n" +
	"Validatepb\xe2\x02\x16Validatepb\\GPBMetadata\xea\x02\n" +
	"Validatepbb\x06proto3"

var (
	file_internal_gin_boot_middleware_validatepb_validate_proto_rawDescOnce sync.Once
	file_internal_gin_boot_middleware_validatepb_validate_proto_rawDescData []byte
)

func file_internal_gin_boot_middleware_validatepb_validate_proto_rawDescGZIP() []byte {
	file_internal_gin_boot_middleware_validatepb_validate_proto_rawDescOnce.Do(func() {
		file_internal_gin_boot_middleware_validatepb_validate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_gin_boot_middleware_validatepb_validate_proto_rawDesc), len(file_internal_gin_boot_middleware_validatepb_validate_proto_rawDesc)))
	})
	return file_internal_gin_boot_middleware_validatepb_validate_proto_rawDescData
}

var file_internal_gin_boot_middleware_validatepb_validate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_gin_boot_middleware_validatepb_validate_proto_goTypes = []any{
	(*ValidateError)(nil), // 0: validatepb.ValidateError
}
var file_internal_gin_boot_middleware_validatepb_validate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_gin_boot_middleware_validatepb_validate_proto_init() }
func file_internal_gin_boot_middleware_validatepb_validate_proto_init() {
	if File_internal_gin_boot_middleware_validatepb_validate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_gin_boot_middleware_validatepb_validate_proto_rawDesc), len(file_internal_gin_boot_middleware_validatepb_validate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_gin_boot_middleware_validatepb_validate_proto_goTypes,
		DependencyIndexes: file_internal_gin_boot_middleware_validatepb_validate_proto_depIdxs,
		MessageInfos:      file_internal_gin_boot_middleware_validatepb_validate_proto_msgTypes,
	}.Build()
	File_internal_gin_boot_middleware_validatepb_validate_proto = out.File
	file_internal_gin_boot_middleware_validatepb_validate_proto_goTypes = nil
	file_internal_gin_boot_middleware_validatepb_validate_proto_depIdxs = nil
}
