// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rbac/rbac.proto

package rbac

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_rbac_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_rbac_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type Hierarchy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          []*Hierarchy_Role      `protobuf:"bytes,1,rep,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hierarchy) Reset() {
	*x = Hierarchy{}
	mi := &file_rbac_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hierarchy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hierarchy) ProtoMessage() {}

func (x *Hierarchy) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hierarchy.ProtoReflect.Descriptor instead.
func (*Hierarchy) Descriptor() ([]byte, []int) {
	return file_rbac_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *Hierarchy) GetRole() []*Hierarchy_Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type Hierarchy_Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Extends       []*Hierarchy_Role      `protobuf:"bytes,3,rep,name=extends,proto3" json:"extends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hierarchy_Role) Reset() {
	*x = Hierarchy_Role{}
	mi := &file_rbac_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hierarchy_Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hierarchy_Role) ProtoMessage() {}

func (x *Hierarchy_Role) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hierarchy_Role.ProtoReflect.Descriptor instead.
func (*Hierarchy_Role) Descriptor() ([]byte, []int) {
	return file_rbac_rbac_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Hierarchy_Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hierarchy_Role) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Hierarchy_Role) GetExtends() []*Hierarchy_Role {
	if x != nil {
		return x.Extends
	}
	return nil
}

var file_rbac_rbac_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Role)(nil),
		Field:         199875362,
		Name:          "ezboot.rbac.role",
		Tag:           "bytes,199875362,opt,name=role",
		Filename:      "rbac/rbac.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Hierarchy)(nil),
		Field:         199875863,
		Name:          "ezboot.rbac.hierarchy",
		Tag:           "bytes,199875863,opt,name=hierarchy",
		Filename:      "rbac/rbac.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional ezboot.rbac.Role role = 199875362;
	E_Role = &file_rbac_rbac_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional ezboot.rbac.Hierarchy hierarchy = 199875863;
	E_Hierarchy = &file_rbac_rbac_proto_extTypes[1]
)

var File_rbac_rbac_proto protoreflect.FileDescriptor

const file_rbac_rbac_proto_rawDesc = "" +
	"\n" +
	"\x0frbac/rbac.proto\x12\vezboot.rbac\x1a google/protobuf/descriptor.proto\".\n" +
	"\x04Role\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"\xa3\x01\n" +
	"\tHierarchy\x12/\n" +
	"\x04role\x18\x01 \x03(\v2\x1b.ezboot.rbac.Hierarchy.RoleR\x04role\x1ae\n" +
	"\x04Role\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x125\n" +
	"\aextends\x18\x03 \x03(\v2\x1b.ezboot.rbac.Hierarchy.RoleR\aextends:H\n" +
	"\x04role\x12\x1e.google.protobuf.MethodOptions\x18\xa2\xb6\xa7_ \x01(\v2\x11.ezboot.rbac.RoleR\x04role:X\n" +
	"\thierarchy\x12\x1f.google.protobuf.ServiceOptions\x18\x97\xba\xa7_ \x01(\v2\x16.ezboot.rbac.HierarchyR\thierarchyB\x87\x01\n" +
	"\x0fcom.ezboot.rbacB\tRbacProtoP\x01Z\x1cgithub.com/ez4bk/ezboot/rbac\xa2\x02\x03ERX\xaa\x02\vEzboot.Rbac\xca\x02\vEzboot\\Rbac\xe2\x02\x17Ezboot\\Rbac\\GPBMetadata\xea\x02\fEzboot::Rbacb\x06proto3"

var (
	file_rbac_rbac_proto_rawDescOnce sync.Once
	file_rbac_rbac_proto_rawDescData []byte
)

func file_rbac_rbac_proto_rawDescGZIP() []byte {
	file_rbac_rbac_proto_rawDescOnce.Do(func() {
		file_rbac_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rbac_rbac_proto_rawDesc), len(file_rbac_rbac_proto_rawDesc)))
	})
	return file_rbac_rbac_proto_rawDescData
}

var file_rbac_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rbac_rbac_proto_goTypes = []any{
	(*Role)(nil),                        // 0: ezboot.rbac.Role
	(*Hierarchy)(nil),                   // 1: ezboot.rbac.Hierarchy
	(*Hierarchy_Role)(nil),              // 2: ezboot.rbac.Hierarchy.Role
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 4: google.protobuf.ServiceOptions
}
var file_rbac_rbac_proto_depIdxs = []int32{
	2, // 0: ezboot.rbac.Hierarchy.role:type_name -> ezboot.rbac.Hierarchy.Role
	2, // 1: ezboot.rbac.Hierarchy.Role.extends:type_name -> ezboot.rbac.Hierarchy.Role
	3, // 2: ezboot.rbac.role:extendee -> google.protobuf.MethodOptions
	4, // 3: ezboot.rbac.hierarchy:extendee -> google.protobuf.ServiceOptions
	0, // 4: ezboot.rbac.role:type_name -> ezboot.rbac.Role
	1, // 5: ezboot.rbac.hierarchy:type_name -> ezboot.rbac.Hierarchy
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rbac_rbac_proto_init() }
func file_rbac_rbac_proto_init() {
	if File_rbac_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rbac_rbac_proto_rawDesc), len(file_rbac_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_rbac_rbac_proto_goTypes,
		DependencyIndexes: file_rbac_rbac_proto_depIdxs,
		MessageInfos:      file_rbac_rbac_proto_msgTypes,
		ExtensionInfos:    file_rbac_rbac_proto_extTypes,
	}.Build()
	File_rbac_rbac_proto = out.File
	file_rbac_rbac_proto_goTypes = nil
	file_rbac_rbac_proto_depIdxs = nil
}
