package gengo

import (
	"bytes"
	"fmt"
	"net/http"
	"os"
	"sort"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/ez4bk/ezboot/cmd/protoc-gen-go-rbac/internal/gengo/template"
	"github.com/ez4bk/ezboot/rbac"
)

// SupportedFeatures reports the set of supported protobuf language features
var SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

var (
	pkgCasbin      = protogen.GoImportPath("github.com/casbin/casbin/v2")
	pkgCasbinRbac  = protogen.GoImportPath("github.com/casbin/casbin/v2/rbac")
	pkgCasbinModel = protogen.GoImportPath("github.com/casbin/casbin/v2/model")

	pkgRbac = protogen.GoImportPath("github.com/ez4bk/ezboot/rbac")
)

// GenerateFile generates the contents of a .pb.go file
func GenerateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if !ShouldGenerate(file) {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_rbac.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	genGeneratedHeader(g, file)
	genVersionHeader(gen, g)
	genGoPackageHeader(g, file)
	genTypeConstraint(g)
	genPolicyLoader(g, file)

	return g
}

func genGeneratedHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-rbac. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
}

func genVersionHeader(gen *protogen.Plugin, g *protogen.GeneratedFile) {
	g.P("// protoc: ", compilerVersion(gen))
	g.P("// protoc-gen-go-rbac: ", Version)
	g.P()
}

func genGoPackageHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("package ", file.GoPackageName)
	g.P()
}

func compilerVersion(gen *protogen.Plugin) string {
	ver := gen.Request.GetCompilerVersion()
	if ver == nil {
		return "(unknown)"
	}

	var suffix string
	if s := ver.GetSuffix(); s != "" {
		suffix = "-" + s
	}

	return fmt.Sprintf("v%d.%d.%d%s",
		ver.GetMajor(), ver.GetMinor(), ver.GetPatch(), suffix)
}

func genTypeConstraint(g *protogen.GeneratedFile) {
	g.P("var _ ", pkgCasbin.Ident("Enforcer"))
	g.P("var _ ", pkgCasbinRbac.Ident("RoleManager"))
	g.P("var _ *", pkgCasbinModel.Ident("Model"))
	g.P("var _ *", pkgRbac.Ident("Def"))
	g.P("var _ *", pkgRbac.Ident("Api"))
}

func genPolicyLoader(g *protogen.GeneratedFile, file *protogen.File) {
	tpl, err := template.LoadTemplate()
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Bad template %s\n", err)
		return
	}

	ctx := &TemplateContext{Pkg: make(map[string]string)}
	ctx.Pkg["model"] = g.QualifiedGoIdent(pkgCasbinModel.Ident("Model"))
	ctx.Pkg["rbacDef"] = g.QualifiedGoIdent(pkgRbac.Ident("Def"))
	ctx.Pkg["rbacApi"] = g.QualifiedGoIdent(pkgRbac.Ident("Api"))
	ctx.Pkg["rbacManager"] = g.QualifiedGoIdent(pkgCasbinRbac.Ident("RoleManager"))

	for _, srv := range file.Services {
		ctx.Services = append(ctx.Services, genServiceTemplateContext(srv))
	}

	var buf bytes.Buffer
	if err = tpl.Execute(&buf, ctx); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Failed to render template %s\n", err)
		return
	}
	g.P(buf.String())
}

type TemplateContext struct {
	Pkg      map[string]string
	Services []*TemplateService
}

type TemplateService struct {
	Name      string
	Policy    []*RolePolicy
	Hierarchy []*RoleHierarchy
	RoleDef   map[string]string
}

func genServiceTemplateContext(srv *protogen.Service) *TemplateService {
	srvCtx := &TemplateService{
		Name:    srv.GoName,
		RoleDef: make(map[string]string),
	}

	for _, method := range srv.Methods {
		role := MethodRBACRole(method)
		srvCtx.RoleDef[role.Name] = role.Desc

		rules := []*annotations.HttpRule{MethodHTTPRule(method)}
		for len(rules) != 0 && role != nil {
			var curr *annotations.HttpRule
			curr, rules = rules[0], rules[1:]

			currPolicy := genRolePolicy(role, curr)
			srvCtx.Policy = append(srvCtx.Policy, currPolicy)
			rules = append(rules, curr.AdditionalBindings...)
		}
	}

	if hierarchy := ServiceHierarchy(srv); hierarchy != nil {
		for _, role := range hierarchy.Role {
			srvCtx.Hierarchy = append(srvCtx.Hierarchy, genRoleHierarchy(role, srvCtx)...)
		}
	}

	sort.Slice(srvCtx.Policy, func(i, j int) bool {
		return srvCtx.Policy[i].Deny
	})

	return srvCtx
}

func genRolePolicy(role *rbac.Role, rule *annotations.HttpRule) *RolePolicy {
	switch pattern := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		return &RolePolicy{Role: role.Name, Method: http.MethodGet, Uri: pattern.Get}
	case *annotations.HttpRule_Put:
		return &RolePolicy{Role: role.Name, Method: http.MethodPut, Uri: pattern.Put}
	case *annotations.HttpRule_Post:
		return &RolePolicy{Role: role.Name, Method: http.MethodPost, Uri: pattern.Post}
	case *annotations.HttpRule_Delete:
		return &RolePolicy{Role: role.Name, Method: http.MethodDelete, Uri: pattern.Delete}
	case *annotations.HttpRule_Patch:
		return &RolePolicy{Role: role.Name, Method: http.MethodPatch, Uri: pattern.Patch}
	default:
		panic("unknown method")
	}
}

type RolePolicy struct {
	Role   string
	Method string
	Uri    string
	Deny   bool
}

func genRoleHierarchy(r *rbac.Hierarchy_Role, ctx *TemplateService) []*RoleHierarchy {
	ctx.RoleDef[r.Name] = r.Desc

	res := []*RoleHierarchy{{Role: r.Name}}
	for _, extend := range r.Extends {
		res[0].Extends = append(res[0].Extends, extend.Name)
		res = append(res, genRoleHierarchy(extend, ctx)...)
	}

	return res
}

type RoleHierarchy struct {
	Role    string
	Extends []string
}
